### ISSUE TITLE
Implement Board Printing Functionality & Extend TicTacToe Start Method to Include Board Print

### ISSUE THREAD

**Issue by zlatica-pernar** [valentinaskn/2023_SLM_TicTacToe_Retro-Realm#25]
- [x] Implement Board Printing Functionality

Task: Develop a function to print the current state of the board in a readable format.

Acceptance Criteria: The board should display the current positions of both players' moves.

- [x] Extend TicTacToe Start Method to Include Board Print

Task: Modify the start method in the TicTacToe class to include a call to the board printing function after each move.
Acceptance Criteria: Each time a move is made, the updated board state is printed.

**Comment by valentinaskn** [comment]
merge request approved & feature branch is successfully merged into main
